//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMWAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopCategory()
        {
            this.ShopCategories1 = new HashSet<ShopCategory>();
            this.ShopProducts = new HashSet<ShopProduct>();
        }
    
        public int Id { get; set; }
        public int ShopId { get; set; }
        public int SysCategoryId { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> Flag { get; set; }
    
        public virtual SysCategory SysCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCategory> ShopCategories1 { get; set; }
        public virtual ShopCategory ShopCategory1 { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProduct> ShopProducts { get; set; }
    }
}
